### ISSUE TITLE
Reject job requests for invalid rounds

### ISSUE THREAD

**Issue by webmaster128** [noislabs/nois-contracts#116]
For incoming job, what is a valid range?

**Comment by webmaster128** [comment]
A full end 2 end solution can currently not be implemented because when the proxy receives an error ack, it does not know which job it belongs to. This is here in the source code: https://github.com/noislabs/nois-contracts/blob/main/contracts/nois-proxy/src/contract.rs#L593-L601

So ideally we just add a range check in the proxy for now to rect invalid requests early on.

**Comment by kaisbaccour** [comment]
has this issue been fixed on the new proxy ?

**Comment by webmaster128** [comment]
What I suggest is move this check from airdrop to the proxy:
https://github.com/noislabs/nois-contracts/pull/243/commits/8fd6d2b9aaee52c27b08e34e68b2142255cfd19e

**Comment by kaisbaccour** [comment]
yeah I think this makes sense. then the tx simulation would also fail right with the same error and same everything?

**Comment by webmaster128** [comment]
Yes. The simulation executes the transaction as if it was in a block. Some data is mocked (e.g. block time is currect time) but the Wasm execution is the same in the simulation.

**Comment by kaisbaccour** [comment]
Very nice. So who takes this task ?

**Comment by webmaster128** [comment]
I'm happy to do this tomorrow. The code chance is small but it's a good opportunity to increase test coverage and finalize version 0.13.5 of the proxy.

**Comment by kaisbaccour** [comment]
nice

**Comment by webmaster128** [comment]
A proxy-based version was added in 0.13.5: https://github.com/noislabs/nois-contracts/pull/247
