### ISSUE TITLE
Implement IBC payment

### ISSUE THREAD

**Issue by kaisbaccour** [noislabs/nois-contracts#155]

**Comment by webmaster128** [comment]
> This is missing only the proxy right ?

Yeah, at least if we are happy with the feature set in #209.

I was wondering if the IBC protocol should have a way to query the price of randomness. But the NOIS chain can only answer "50 NOIS" but does not know thich is the correct IBC denom. However, if you hardcode the denom than this would allow the proxy to query for price updates occasionally.

**Comment by webmaster128** [comment]
Done in #209. Fingers cross it includes all we need.
